services:
  parser:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./dumps:/app/dumps
    command: python parser/parser.py
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5008:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
